### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by ArtemeeSenin** [jas-chen/atom-live-server#102]
I try to start it, but I get the message "the server is stopped", I press ctrl+alt+l, or I press ctrl+alt+q it gives the same message, and ctrl+alt+3 does not do anyting.
Also if I restart atom and try to launch in the menu, the atom-live-server just dissapears.

I have updated atom, by downloading install from atom.io, I've tried firstly stable and then beta versions but nothing changes.

**Comment by branen890** [comment]
I have same problem...I

**Comment by branen890** [comment]
ArtemeeSenin just add in your PATH C:\Windows\System32.

**Comment by LemonyPie** [comment]
Thank you! Possibly that should work :)
