### ISSUE TITLE
not working,even it is not available in menu

### ISSUE THREAD

**Issue by cvs0986** [jas-chen/atom-live-server#108]
If you have a problem launching a live-server, please try following steps:

1. Make sure you use the right hotkeys. After v2.0.0, the keys became `ctrl-alt` combination.
2. Try launching live-server from top menu: `Package -> live-server -> Start Server` to see if it works.

**Comment by jas-chen** [comment]
plz upgrade to v2.2.0.

**Comment by cvs0986** [comment]
It started working fine.

Thanks for the reply.


Kind Regards,
Veer Singh
+91 886 089 9771





On 11-Oct-2017, at 2:31 PM, Jas Chen <notifications@github.com<mailto:notifications@github.com>> wrote:


plz upgrade to v2.2.0.
