### ISSUE TITLE
How to stop running live server ?

### ISSUE THREAD

**Issue by agupta1989** [jas-chen/atom-live-server#11]
Hi, its kind of query cum issue I can say. Question is, How are we suppose to shut down the running live server ? For e.g. If I press Ctr+Shift+3 and it will run the app on port 3000. then if I close the browser / tab and again trying to run the same application on port 3000, its not working. its opening on some random ports. So there is two server running on different port. Any thought ?

**Comment by jas-chen** [comment]
Restart Atom editor or [reload packages](https://discuss.atom.io/t/reload-a-package-while-developing/432/10).

**Comment by agupta1989** [comment]
@jas-chen yeah.. I am doing the same i.e. restarting Atom. I thought there would be some feature to stop them. is it expected in future release ?

**Comment by jas-chen** [comment]
@agupta1989 I'll think about it, however, I would like to keep this package as simple to use as possible, adding more hotkeys or UI on it is not what I want.

**Comment by agupta1989** [comment]
Ok, that's right. just for example (if you havn't already), have a look on Bracket's Live Preview (in-build feature). moment we close browser or tab, live preview stop the integrated server. but anyway I will close this issue. Thank you for your updates :)

**Comment by sahamalam** [comment]
![capture](https://user-images.githubusercontent.com/30209329/28518346-2ea57a00-7085-11e7-8705-ca0cb7111046.PNG)
unable to run file with atom live server. 
guide me to setup ports,

**Comment by cristianpenia** [comment]
you can close the application and then go to the task manager and also finish it there 

![Captura de pantalla (82)](https://user-images.githubusercontent.com/48634410/62683831-fe9c7980-b984-11e9-97ba-f8e6d01a26ab.png)

that will be enough to stop the server

**Comment by cristianpenia** [comment]
you can close the application and then go to the task manager and also finish it there 

![Captura de pantalla (82)](https://user-images.githubusercontent.com/48634410/62683831-fe9c7980-b984-11e9-97ba-f8e6d01a26ab.png)

that will be enough to stop the server
