### ISSUE TITLE
'delay' option

### ISSUE THREAD

**Issue by flcoder** [jas-chen/atom-live-server#114]
This is a great package for me but one frustrating thing is that I always have to save my files twice in order to see new content.  My guess is that my browserify is publishing the map file before the script or something like that.  I think a 100-200ms delay before actual page reload would solve the issue I'm having.  A setting in .atom-live-server.json would be great.  Thanks for this!

**Comment by jas-chen** [comment]
There's a `wait` option in live-server, have you tried it?

**Comment by flcoder** [comment]
I didn't see it in the docs, I will try it.

**Comment by flcoder** [comment]
Works perfect. Thanks!
