### ISSUE TITLE
Can I choose browser(other than default)

### ISSUE THREAD

**Issue by Kenshasa** [jas-chen/atom-live-server#12]
I have Chrome as my default, but if I want to test in a different browser(safari, firefox, canary, etc) can you show me here I can make this change without breaking this wonderful package?

Thanks in advance!

**Comment by jas-chen** [comment]
Hi @Kenshasa,
No problem, I'll add this feature when I get free time. Thanks for the suggestion!

**Comment by umi-gary** [comment]
I have Chrome set as my default browser, but live-server opens in firefox.
I would also like to have the ability to open in a different browser.

**Comment by jas-chen** [comment]
Fixed in v2.0.0.

**Comment by armenjuhl** [comment]
H Jas-Chen. Thank you for your work. It would be great if you could give the instructions for how to select a different default browser once it is set.

**Comment by jayfredo** [comment]
I have live server installed, but when I launch the server only my home screen pops up. am I doing something wrong?

**Comment by jas-chen** [comment]
plz open new issue for new issue
