### ISSUE TITLE
How to ignore some files ?

### ISSUE THREAD

**Issue by MLefebvreICO** [jas-chen/atom-live-server#13]
Hi, 

I want to be able to tell live-server to ignore some files modification for the live-reload feature.
Is that possible ? If so how ? If not, can this come in a next release ?

I'm using this with typescript projet, so I want to ignore file changes on `.ts` and instead listen to the change on the compiled `.js`

**Comment by jas-chen** [comment]
Hi,

This feature is not supported yet, you can use original [Live-Server](https://github.com/tapio/live-server) to do that.

**Comment by jas-chen** [comment]
Fixed in v2.0.0.
