### ISSUE TITLE
Localhost:t5000

### ISSUE THREAD

**Issue by iepoch** [jas-chen/atom-live-server#142]
When using the donet run to run a local applications it will run on localhost:5000, however, when I run atom live server it defaults to different servers an not to Localhost:5000. When using the ctrl alt 5 command it shows 1000 or 3000 and doesn't ever go to 5000. I am not sure what it the problem.

**Comment by jas-chen** [comment]
seems like something already running on port 5000, so it can't run on that port.

**Comment by iepoch** [comment]
I thought that as well. So I made sure nothing was running on that port including any dotnet run. And I still got the same result. Now what I do know is when you run an asp.net application and it runs on port 5000. Even if stoping the application and making sure nothing is using the port. When you try using the atom live server and use the port 5000 it will go to a completely different port number. I even went as far as restarting the computer

**Comment by iepoch** [comment]
Did not get a solid response. And moved on to VSCode
