### ISSUE TITLE
shoertcut to open server logs out of ubuntu

### ISSUE THREAD

**Issue by koopaTroopa1** [jas-chen/atom-live-server#153]
I use ubuntu linux as my os. The keyboard shortcut to launch the live server is ctrl-alt-L, which logs out of the current user account on ubuntu, and goes to the login screen. can you add a way to change this shortcut for ubuntu users?

**Comment by jas-chen** [comment]
https://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/
