### ISSUE TITLE
No Refresh on Save

### ISSUE THREAD

**Issue by bennyp123** [jas-chen/atom-live-server#16]
I'm not getting refresh on save behaviour.
Please advise how to test.

**Comment by jas-chen** [comment]
Can you see your page via localhost?

**Comment by bennyp123** [comment]
Page loads up just fine in a new tab (chrome) at 127.0.0.1:PORT when I
activate the server. Just when I save the file (html or css) it doesn't
reload

On Tue, May 3, 2016, 4:21 AM Jas Chen <notifications@github.com> wrote:

> Can you see your page via localhost?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jas-chen/atom-live-server/issues/16#issuecomment-216410762>
>
-- 
Benny Powers
Licensed Israel Tour Guide

In Israel 054-482-5726
In Canada 705-300-0072
In the USA 601-255-3532

bennypowers.com

**Comment by jas-chen** [comment]
Maybe you can setup a minimal project to see if it works?

**Comment by bennyp123** [comment]
Can confirm that in a project with 

    index.html
    css/master.css

livereload works just fine

Problematic project has 

    index.html
    assets/styles.css
    .editorconfig
    gulpfile.js
    .gitignore // MyFiles/ 
    MyFiles/**/*

removing .editorconfig, gulpfile, and commenting out links to CDN based resources in index didn't affect livereload behaviour.

**Comment by bennyp123** [comment]
The problem was caused by missing `body` close tag
