### ISSUE TITLE
No way to stop atom live server

### ISSUE THREAD

**Issue by Mayankjh** [jas-chen/atom-live-server#162]
when i turn on the server there is no way i can stop from menu option  in the current version previously we had stop server tab on the packages menu that doesn't seem to appear any more.

**Comment by pimkennedy** [comment]
Same here.

**Comment by matikken** [comment]
the same problem, This atom-live-server is one big BUG.

**Comment by richiksc** [comment]
This issue was fixed in v2.3.0 (commit ff7ca9d).
