### ISSUE TITLE
Uncaught SyntaxError: Unexpected '#' at line 1 column 2 of the JSON5 data. Still to read: "# This...

### ISSUE THREAD

**Issue by cornelius80** [jas-chen/atom-live-server#184]
Hi jas-chen,
I have encountered an error while trying to fire up atom-live-server. 
It doesn't seem to play nice with JSON5, I'd pressum?

The following are my steps to reproduce the error.
 
1. Upgraded atom 1.27.1-1 to 1.27.2-2 on antergos Linux.
2. Fire up atom-live-server and the encountered the error.

Please advise.

Regards,
Cornelius

**Atom**: 1.27.2 x64
**Electron**: 1.8.4
**OS**: linux 4.16.12-1-ARCH
**Thrown From**: [atom-live-server](https://github.com/jas-chen/atom-live-server) package 2.3.0

### Stack Trace

Uncaught SyntaxError: Unexpected '#' at line 1 column 2 of the JSON5 data. Still to read: "# This version is up"

```
At /home/cornelius/.atom/packages/atom-live-server/node_modules/json5/lib/json5.js:64

SyntaxError: Unexpected '#' at line 1 column 2 of the JSON5 data. Still to read: "# This version is up"
    at error (/packages/atom-live-server/node_modules/json5/lib/json5.js:56:25)
    at word (/packages/atom-live-server/node_modules/json5/lib/json5.js:393:13)
    at value (/packages/atom-live-server/node_modules/json5/lib/json5.js:493:56)
    at Object.parse (/packages/atom-live-server/node_modules/json5/lib/json5.js:508:18)
    at /packages/atom-live-server/lib/atom-live-server.js:137:34
    at /packages/atom-live-server/lib/atom-live-server.js:152:12
    at FSReqWrap.oncomplete (fs.js:135:15)
```

### Commands

```
     -0:23.1.0 atom-live-server:startServer (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-bracket-highlight 0.3.2 
atom-live-server 2.3.0 
autoclose-html 0.23.0 
autocomplete-modules 2.0.0 
docker 0.8.0 
file-icons 2.1.21 
git-plus 7.10.2 
gitlab-integration 0.4.7 
highlight-selected 0.13.1 
minimap 4.29.8 
platformio-ide-terminal 2.8.2 
remote-ftp 2.2.0 
tree-view-git-status 1.5.0 
```

**Comment by jas-chen** [comment]
Could u provide ur atom-live-server.json file?

**Comment by cornelius80** [comment]
Hi Jas-chen,

Thank you for your kind response.
I think I might have solved the issue by using a different copy of my project. The error suddenly disappeared.
However, if it helps. The following is my atom-live-server.json file you requested.


`{
  "browser":"/usr/bin/firefox",
  "entry-file":"index.html"
}`

Thank you once again and Kind Regards,
Cornelius
