### ISSUE TITLE
Use index.html for every request

### ISSUE THREAD

**Issue by stevedeighton** [jas-chen/atom-live-server#19]
This is the 'file' option on the live server project if I run through node, but I want to use the sweet package for atom!  How do I configure the 'file' parameter so that it runs index.html for every request, as I am developing a single page app.

Reference here: 
https://www.npmjs.com/package/live-server

Thanks!

**Comment by jas-chen** [comment]
Hi @stevedeighton,

Thanks for your advice, I'll consider to implement this feature when I got some free time.
