### ISSUE TITLE
Invisible everywhere

### ISSUE THREAD

**Issue by ricalonso58** [jas-chen/atom-live-server#194]
Live Server does not show up in the Packages menu. Using the ctrl-alt-l just brings up the Key Binding Resolver.  I have uninstalled and reinstalled atom-live-server. I have upgraded Atom to the latest version. I have rebooted my Mac. 
It used to work great but now it's completely unavailable.
Thank you for your help.
![image](https://user-images.githubusercontent.com/26491073/43555603-0aa4a99a-95b0-11e8-8c98-62bb2be6ba38.png)
![image](https://user-images.githubusercontent.com/26491073/43555611-18d77d26-95b0-11e8-8048-70a6318bd96a.png)

**Comment by jas-chen** [comment]
#57
