### ISSUE TITLE
Can't install the package

### ISSUE THREAD

**Issue by frodoe7** [jas-chen/atom-live-server#20]
Hello
I can't install the package
I am getting this error
operating system : windows 10
## Installing “atom-live-server@1.2.5” failed

npm WARN excluding symbolic link live-server\node_modules.bin\watchr -> ../watchr/bin/watchr
npm WARN excluding symbolic link live-server\node_modules\send\node_modules.bin\mime -> ../mime/cli.js
npm WARN excluding symbolic link live-server\node_modules.bin\watchr -> ../watchr/bin/watchr
npm WARN excluding symbolic link live-server\node_modules\send\node_modules.bin\mime -> ../mime/cli.js
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\Mohsen\AppData\Local\atom\app-1.8.0\resources\app\apm\bin\node.exe" "C:\Users\Mohsen\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\Mohsen\.atom\.apm\.apmrc" "--userconfig" "C:\Users\Mohsen\.atom\.apmrc" "install" "C:\Users\Mohsen\AppData\Local\Temp\d-11668-788-wg4rsl\package.tgz" "--target=0.36.8" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file C:\Users\Mohsen.atom.apm\bal-util\1.18.0\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\Mohsen.atom.apm\bal-util\1.18.0\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by jas-chen** [comment]
I'm going to close this v1.x issue. Please upgrade to v2.0.0.
