### ISSUE TITLE
Doesn't load at automatically

### ISSUE THREAD

**Issue by rayhansenjr** [jas-chen/atom-live-server#21]
Doesn't work until I uninstall and reinstall every time i reopen atom.

I'm using it on windows 10 and the version is 1.2.5

**Comment by Kenshasa** [comment]
Having the same issue, however restarting and re-installing doesn't help. However is does to seem to work fairly consistently on my Mac...go figure.

**Comment by jas-chen** [comment]
Is there any error message? It works on my Mac.

**Comment by pingshunhuangalex** [comment]
The auto-refresh doesn't work on my Windows 10 either. No error message.

Another weird thing is shortcut for launching port 8000 only works once, if the window is opened and closed, then ctrl+shift+8 won't open port 8000, instead it'll launch something else. I have to close atom and fire it up again to get it work, and again it's a one-time thing.

**Comment by jas-chen** [comment]
I'm going to close this v1.x issue. Please upgrade to v2.0.0.

**Comment by Raheel32** [comment]
atom live server doesn't run it says that application not found. 
what i'm gonna do?

**Comment by Rjayam** [comment]
Atom-Live-Server is not launching the browser automatically. But the script running on port 3000. what should i do to start it automatically. I am ;using Atom-Live-Server ver.2.3.0
