### ISSUE TITLE
If Atom is closed before the live-server is disabled, the server stays awake.

### ISSUE THREAD

**Issue by Fuwn** [jas-chen/atom-live-server#220]
# How

1. Started live-server
2. Closed Atom

I can start and stop new live server but my original one that I started cannot be stopped.

**Comment by s1nical** [comment]
### Resolved this in CMD using;

1. netstat -ano | findstr :**portnumber**
2. taskkill /PID **pididentifier** /F

> PID meaning Proccess Identifier

[![](https://img.shields.io/badge/Image%20Reference-%3C3-green.svg)](https://imgur.com/a/9EBhOzY)

**Comment by setanarut** [comment]
@8cy Doesn't work on macOS
```
% netstat -ano | findstr :3000
zsh: command not found: findstr
```
this works.
`lsof -ti:3000 | xargs kill`
