### ISSUE TITLE
 I have tried to start the package, and when I do, all I see is the following "Live-Server stops" massage. Even when I turn it off, it shows me the same massage. I tried to uninstall it, close it and open it again, and nothing. I do not know what could I do.

### ISSUE THREAD

**Issue by LucioFex** [jas-chen/atom-live-server#242]
I'm getting the following message:

 "If you have a problem launching a live-server, please try following steps:
1. Make sure you use the right hotkeys. After v2.0.0, the keys became `ctrl-alt` combination.
 2. Try launching live-server from top menu: `Package -> live-server -> Start Server` to see if it works."

**Comment by jkvandervliet** [comment]
None of those options work. I am having the same issues. Any of the hotkeys pressed results in Live Server Stopped message. Same thing from the top menu.

**Comment by johno1566** [comment]
I am also having this issue
