### ISSUE TITLE
does not work 

### ISSUE THREAD

**Issue by asoong-94** [jas-chen/atom-live-server#26]

**Comment by asoong-94** [comment]
ctrl-shift-3 does nothing, same for all the other key bindings

**Comment by Esslamb** [comment]
I seem to be having the same problem.

**Comment by janstieler** [comment]
On which OS you are?

**Comment by Esslamb** [comment]
I eventually found that the it was just ctrl-shift-3 that wasn't working so I assume the port was just being used for something else. The others worked fine for me.

**Comment by JamalANasier** [comment]
@asoong-94 would you close this issue ? the title is annoying

**Comment by jas-chen** [comment]
Let me close this
