### ISSUE TITLE
Browser Launch

### ISSUE THREAD

**Issue by IanNTFT** [jas-chen/atom-live-server#29]
For our students we currently block access to cmd.exe via group policy, would this stop the browser from launching?

**Comment by jas-chen** [comment]
I use macOS, so I cannot give you an answer, please try it yourself. Sorry.

**Comment by IanNTFT** [comment]
Setting the registry key HKCU\Software\Policies\Microsoft\Windows\System\DisableCMD to REG_DWORD 00000001 stops users from accessing the Command Prompt but also seems to live-server launching a browser.
Is live-server using an atom provided API to do this browser launch? If so, where is the best place to log the issue?

**Comment by jas-chen** [comment]
I don't know. I'm not the author of [live-server](https://github.com/tapio/live-server).

**Comment by jas-chen** [comment]
I'm going to close this v1.x issue. Please upgrade to v2.0.0.
