### ISSUE TITLE
PHP files dont work

### ISSUE THREAD

**Issue by KinglyDeveloper** [jas-chen/atom-live-server#32]
I was wondering how I might be able to load PHP files because when I click them it just downloads, it doesn't open.

**Comment by jas-chen** [comment]
PHP files are not support.

**Comment by gusbemacbe** [comment]
@jas-chen, maybe you should learn from the package https://github.com/leijou/php-server.

**Comment by jas-chen** [comment]
@gusbemacbe, maybe you should learn go or Rails.
