### ISSUE TITLE
Could it automatically locate the page being edited?

### ISSUE THREAD

**Issue by pureliumy** [jas-chen/atom-live-server#33]
This package locates the root of project folder when I launch it, and I hope it can automatically locate the page being edited. 
Is there any way I can make it solved?

**Comment by TrevorBurnham** [comment]
I'd also like to see this. Perhaps a separate key binding for "Launch server for current file."

**Comment by TrevorBurnham** [comment]
I wound up creating my own Atom plugin to do this: https://github.com/TrevorBurnham/local-web-server

**Comment by jas-chen** [comment]
@TrevorBurnham it looks nice!

**Comment by jas-chen** [comment]
Fix in v2.0.0.
