### ISSUE TITLE
refresh on save not working

### ISSUE THREAD

**Issue by mconnor** [jas-chen/atom-live-server#34]
Everything has been working as expected. But suddenly the browser is not refreshing when changes are made to my html. I've tried on different ports. No luck.

**Comment by jordanblakey** [comment]
###Awesome awesome plugin but I am also experiencing this issue. 
Tried on several ports, save, then nothing until manual reload.

**Comment by jas-chen** [comment]
I'm going to close this v1.x issue. Please upgrade to v2.0.0.
