### ISSUE TITLE
#live preview of css and html is not working

### ISSUE THREAD

**Issue by Tikam02** [jas-chen/atom-live-server#35]
atom-live server package  runs on internet but its not working propely.Like files are opening but its not giving live output as edited in the text-editor.
Please can someone explain in brief that ports are not working and css live preview is not working.

ctrl-shift-3 launch live server on port 3000.

ctrl-shift-4 launch live server on port 4000.

ctrl-shift-5 launch live server on port 5000.

ctrl-shift-8 launch live server on port 8000.

ctrl-shift-9 launch live server on port 9000.

**Comment by Wade-BuildOtto** [comment]
same here, I just updated atom to 1.12.7 and started having errors with live server either project is not open or saves don't update the preview.

**Comment by Wade-BuildOtto** [comment]
and or its something with atom, its occasionally not saving the files I closed and re-opened and the changes I made were lost. re-added and run live server again and its back working again.

**Comment by jordanblakey** [comment]
I'm also having this issue. On save, no auto reload. Version 1.12.7.

**Comment by jas-chen** [comment]
I'm going to close this v1.x issue. Please upgrade to v2.0.0.
