### ISSUE TITLE
'Failed to spawn command' after 2.1.0 update

### ISSUE THREAD

**Issue by thancock20** [jas-chen/atom-live-server#42]
Using Linux Mint 17.3

Everything worked fine in v2.0.0, but after updating to v2.1.0 when I try to launch live-server it opens the dev-tools and gives the following error:

Failed to spawn command
`/resources/app/apm/bin/node`. Make sure `/resources/app/apm/bin/node` is installed and on your PATH

When I run `which node` in my terminal I get `/usr/bin/node`. I'm not sure why the package is looking for a `resources` directory in my root (`/`) directory, but there's obviously not one there.

**Comment by jas-chen** [comment]
Please follow this issue in #40.
