### ISSUE TITLE
Can not override key configuration

### ISSUE THREAD

**Issue by FrankenApps** [jas-chen/atom-live-server#49]
If I start the Server via:  `Package -> live-server -> Start Server` it does work as I am used to it. However after the recent update the Hotkeys changed. I can not use these Hotkeys, because I have a german layout keyboard and for example `ctrl-alt-9` writes some kind of weird symbol. So I tried overriding the new commands with the old ones in my `keymap.cson`. But it did not work.
![changekeymap](https://cloud.githubusercontent.com/assets/17967303/23173013/13cdf1f8-f858-11e6-8c9d-958fb5de2be3.png)
![changekeymap2](https://cloud.githubusercontent.com/assets/17967303/23173020/1947b0ce-f858-11e6-8943-0e16d9208742.png)
As one can see above it did seem to work, however the server does not launch. Is it somehow not possible to override the default keymaps, or am I doing something wrong here?
Thanks in advance

**Comment by jas-chen** [comment]
`ctrl-shift-9` somehow doesn't work anymore, that's why I switched to the new key bindings. However, `ctrl-p` works fine. 😂

**Comment by FrankenApps** [comment]
Okay that worked, thank you.
