### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by kostaskol** [jas-chen/atom-live-server#50]
-- Reproduction --
1. link /usr/bin/node to /usr/lib/app/apm/bin/node

-- OS --
Arch Linux

-- Description --
After pressing Ctrl + Alt + 3 this error appears
It doesn't appear when pressing Ctrl + Alt + 1|2, but the server does not work either

The error used to be different. At first it said that node could not be spawned and that I should make sure that node exists in /usr/lib/app/apm/bin/node (which I did by linking it with my existing installation)

If any further details are required, feel free to ask

**Atom**: 1.14.3 x64
**Electron**: 1.4.15
**OS**: "Arch Linux"
**Thrown From**: [atom-live-server](https://github.com/jas-chen/atom-live-server) package 2.1.1

### Stack Trace

Uncaught Error: spawn EACCES

```
At /usr/lib/atom/src/buffered-process.js:357

Error: spawn EACCES
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:392:9)
    at BufferedProcess.spawn (/usr/lib/atom/src/buffered-process.js:286:51)
    at new BufferedProcess (/usr/lib/atom/src/buffered-process.js:89:12)
    at /packages/atom-live-server/lib/atom-live-server.js:123:23
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -0:21.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
     -0:02.0 atom-live-server:start-3000 (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.29.17 
atom-espresso-soda-theme 0.10.0 
atom-htmltidy 5.1.0 
atom-live-server 2.1.1 
atom-monokai 0.10.9 
autoclose-html 0.23.0 
autocomplete-angular-material 0.4.0 
autocomplete-python 1.8.57 
file-icons 2.0.15 
highlight-selected 0.12.0 
linter 1.11.23 
linter-gcc 0.7.1 
linter-python 3.0.5 
minimap 4.26.8 
minimap-find-and-replace 4.5.1 
minimap-highlight-selected 4.5.0 
monokai 0.22.0 
monokai-blackboard 0.3.0 
monokai-complete-syntax 0.2.3 
monokai-dark 1.3.0 
monokai-flat 1.0.1 
monokai-plus 0.1.3 
monokai-seti 0.7.0 
monokai-shade 0.3.5 
monokai-slate 0.6.0 
python-tools 0.6.9 
sub-monokai 1.2.4 
textmate-espresso-libre-syntax 0.1.0 
textmate-espresso-syntax 0.1.0 
textmate-espresso-tutti-syntax 0.1.0 
todo 0.6.0 
```

**Comment by jas-chen** [comment]
I googled `spawn EACCES` and find it was due to Atom has no permissions to run that command. You need to run `chmod` command to grant permissions.
