### ISSUE TITLE
Stopped working after update 2.1.2

### ISSUE THREAD

**Issue by Supertechie2010** [jas-chen/atom-live-server#51]
I have tried these two suggestions and neither works, was functioning prior to 2.1.2 update and as soon as updated it stopped functioning I have tried reinstalling as well as restarting. 

If you have a problem launching a live-server, please try following steps:

1. Make sure you use the right hotkeys. After v2.0.0, the keys became `ctrl-alt` combination.
2. Try launching live-server from top menu: `Package -> live-server -> Start Server` to see if it works.

**Comment by jas-chen** [comment]
@Supertechie2010 what OS are you using? Can you open devTool and see if any log message shows up?

**Comment by Supertechie2010** [comment]
Fixed the issue it ended up being a windows ossue something locked up the
ports.


On Feb 28, 2017 9:51 PM, "Jas Chen" <notifications@github.com> wrote:

@Supertechie2010 <https://github.com/Supertechie2010> what OS are you
using? Can you open devTool and see if any log message shows up?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jas-chen/atom-live-server/issues/51#issuecomment-283229745>,
or mute the thread
