### ISSUE TITLE
Problem with using this program

### ISSUE THREAD

**Issue by njanne19** [jas-chen/atom-live-server#59]
I have this package installed on Atom, however the hotkeys that are assigned don't work, and the package does not come up in the packages tab of OSX. I'm not sure what to do, because it claims it is installed but appears not to be.

**Comment by amants** [comment]
I'm having the same issue! As I have an exam tomorrow, can you please look into this asap?

**Comment by Tony-Thomas** [comment]
Same problem here

**Comment by jas-chen** [comment]
https://github.com/jas-chen/atom-live-server/issues/57#issuecomment-303145278
