### ISSUE TITLE
Remove console.log('Live reload enabled.');

### ISSUE THREAD

**Issue by satrya** [jas-chen/atom-live-server#6]
Hi,
Thank you for the package, but please remove the `console.log('Live reload enabled.');` code. I'm using dev tool a lot and I feel a bit weird to see that words while I'm debugging my code.

Thank you.

**Comment by jas-chen** [comment]
@satrya this code is in the original live-server library so I can't remove it, but you can do it yourself.

Open `~/.atom/packages/atom-live-server/live-server/injected.html` and remove the code, save the file and restart atom editor.

If the log message is still there, try to clear the browser cache.

**Comment by satrya** [comment]
I see, thank you @jas-chen

**Comment by AAhrit** [comment]
@jas-chen 

> @satrya this code is in the original live-server library so I can't remove it, but you can do it yourself. Open~/.atom/packages/atom-live-server/live-server/injected.html and remove the code, save the file and restart atom editor.

Where in visual studio code can I do the same?

**Comment by AmanKrMandal** [comment]
> Hi, Thank you for the package, but please remove the `console.log('Live reload enabled.');` code. I'm using dev tool a lot and I feel a bit weird to see that words while I'm debugging my code.
> 
> Thank you.

same problem with me . it little bit irritating, how to resolve
