### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by santhoshgotur** [jas-chen/atom-live-server#62]
Unable to start the atom-live-server on mac. Even though i installed the package, I dont see the option under packages tab.

<img width="1285" alt="screen shot 2017-06-09 at 12 00 00 am" src="https://user-images.githubusercontent.com/11220812/26964503-a195e9a8-4ca6-11e7-823c-18b0f877d7a3.png">

**Comment by jas-chen** [comment]
https://github.com/jas-chen/atom-live-server/issues/57#issuecomment-303145278

**Comment by santhoshgotur** [comment]
Thank you.  That fixed the issue
