### ISSUE TITLE
Not Working in MAc

### ISSUE THREAD

**Issue by rsaxena315** [jas-chen/atom-live-server#66]
Not working in mac 
Not able to see list of package installed

**Comment by donmozza** [comment]
Ive got the same issue. The package installs but it doesn't who up in the Packages Menu, and doesn't seem to be running.

**Comment by donmozza** [comment]
I'm running 2.1.2 with Atom 1.18.0 x64, running on MacOS Sierra.

**Comment by jas-chen** [comment]
#57
