### ISSUE TITLE
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

### ISSUE THREAD

**Issue by wzs28150** [jas-chen/atom-live-server#67]
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.3.15/iojs-v1.3.15.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: connect ETIMEDOUT 54.231.120.147:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1022:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1045:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\wzs\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\wzs\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=1.3.15" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd C:\Users\wzs\.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by ElijahPrince73** [comment]
I got a similar issue when I downloaded the package.

Have you rebuilt the plugin?

**Comment by beschio** [comment]
@jas-chen Fixed it for me. Thanks!
