### ISSUE TITLE
"failed to spawn command"

### ISSUE THREAD

**Issue by WToimi** [jas-chen/atom-live-server#68]
`Failed to spawn command /usr/lib/app/apm/bin/node. Make sure /usr/lib/app/apm/bin/node is installed and on your PATH`

I get this error as soon as i try to launch the package, it simply doesn't work :o 
I'm on arch linux.

**Comment by d1729** [comment]
Though I am using mac, I also get the same message.. any solutions yet?

**Comment by WToimi** [comment]
Uuh i seem to have solved it, i just downloaded the "atom-editor-bin" from the AUR. It worked after that. I'm not running arch anymore though. Now i use debian and now it runs great.
