### ISSUE TITLE
Making changes in CSS file is not reflected in web browser

### ISSUE THREAD

**Issue by sparkeplug** [jas-chen/atom-live-server#7]
Hi,

Everything was working perfect ,but most of the times the changes made in CSS file is not reflecting in the browser after saving. But  when the HTML file is saved again ,the changes are reflected. This problem is inconsistent .

**Comment by jas-chen** [comment]
Live-server will only watch the files in the project folder, you have to put css files inside the same folder as HTML files.

**Comment by sparkeplug** [comment]
FYI, this is my project folder. Everything is under the same project folder. 

Even after trying by placing the css file next to the index.html, still i can only see the changes reflected when saving HTML files only and not while saving CSS.
 
![atom live server issue](https://cloud.githubusercontent.com/assets/10337388/11678472/504cc568-9e6e-11e5-9342-d89d9bcd96ff.jpg)

**Comment by jas-chen** [comment]
That is weird, css reloading works on my machine (Mac OSX).
Maybe you can create another tiny project to test it out? Sorry for that...

**Comment by sparkeplug** [comment]
Hi , 
Found out that other test project is working fine. Any idea where would the problem lie in my old project....

FYI, ....  

Used BOWER components,
Used NPM modules,
Is an Angular project......,
And is GIT synced project....

Any Idea chen ?

**Comment by sparkeplug** [comment]
FOUND THE PROBLEM CHEN......

"Syntax error in my HTML caused the css error... even though the HTML renders each time"

**Comment by jas-chen** [comment]
:+1:

**Comment by Sumbro2000** [comment]
This is a pretty basic answer but might help some newbies out there, as it did me. Try opening your page in a different browser. If your changes appear there, then they have been implemented in your child theme. If that's the case, go back to your original browser (in my case, it was Chrome) and clear your cache. I was pointing the finger at Atom (my text editor) when really the issue was that Chrome was trying to be "helpful."

**Comment by caigner** [comment]
In my project, I use default.css which in turn loads via @import base.css.

When making a change in base.css, only default.css is reloaded.

Any ideas?
