### ISSUE TITLE
server not recognizing working directory (windows 10)

### ISSUE THREAD

**Issue by ansachs** [jas-chen/atom-live-server#73]
When I start a server , the program thinks my desktop is the working directory, and serves everything. I tried changing the project directory, etc

**Comment by jas-chen** [comment]
Doesn't `root` option work?

**Comment by ansachs** [comment]
I tried putting:
```
{
  "root": "public"
}
```

in a json file and it did nothing

**Comment by ansachs** [comment]
nm, i figured it out. it defaults to desktop, had to put json there
