### ISSUE TITLE
Unable to run as package chashes.

### ISSUE THREAD

**Issue by clemens-tolboom** [jas-chen/atom-live-server#74]
> Failed to require the main module of 'atom-live-server' because it requires one or more incompatible native modules (binding, binding, binding, binding, binding, binding).
Run `apm rebuild` in the package directory and restart Atom to resolve.

There is no entry for (logically)
> Try launching live-server from top menu: `Package -> live-server -> Start Server` to see if it works.

What will happen when rebuilding all?

> /Users/clemens/.atom/packages % apm rebuild --help
>Usage: apm rebuild [<name> [<name> ...]]
>
>Rebuild the given modules currently installed in the node_modules folder
>in the current working directory.
>
>All the modules will be rebuilt if no module names are specified.

**Comment by clemens-tolboom** [comment]
`apm rebuild` did not help. With or without atom-live-server package only

**Comment by jas-chen** [comment]
#57

**Comment by clemens-tolboom** [comment]
Thanks for the XREF!
