### ISSUE TITLE
atom-live-server does not appear in packages and wont run... just nothing!

### ISSUE THREAD

**Issue by BringBackThe80s** [jas-chen/atom-live-server#76]
Hi,
So I am a bit of a noob but I have installed atom on my mac (editor works fine) and installed live-server.
I am unable to start ls, and although it appears to be installed in settings i.e. I can disable or uninstall it, it is not listed under the packages drop down - also tried the hotkeys for my version.
Ive tried uninstalling and reinstalling a few times, even following instructions to remove hidden files etc courtesy of Google. It just looks like its not there...

Versions: atom 1.18.0 X64, live-server 2.1.2, running on Mac OS Sierra 10.12.5

**Comment by jas-chen** [comment]
#57

**Comment by BringBackThe80s** [comment]
Thanks, sorry for the double up.
Its working now.

**Comment by ashish234251** [comment]
I am having the same problem..how did you solve it..
