### ISSUE TITLE
Live Server Requires Manual Refresh

### ISSUE THREAD

**Issue by Matthew-Christopher** [jas-chen/atom-live-server#81]
Hi, I'm using Windows 10 and the latest version of Atom and atom-live-server. I've tried reinstalls, stopping the server and starting it again etc but I simply cannot get the live reload functionality to work. Perhaps I am misunderstanding what this should be doing? The server loads fine and I can access the web pages but if I update the code and save it nothing updates in the browser window until I refresh the page. No issues are reported in the console and I only see: "Live reload enabled."

**Comment by jackputtock** [comment]
Hi Matt, I have installed this as well but I am not having the same issue, it could be something to do with your firewall but I would class this as unlikely. Mine is slightly delayed by about 4 seconds, so when I save it will take 4 seconds to update. So that is my only issue with this plugin.

**Comment by Matthew-Christopher** [comment]
Firewall access permitted. I'm now using [LiveReload](http://livereload.com/) instead to work around this issue.

**Comment by jackputtock** [comment]
Ok. At lease the issue is fixed.
