### ISSUE TITLE
Doesn't appear in menus

### ISSUE THREAD

**Issue by gantonia** [jas-chen/atom-live-server#82]
I've installed it twice and restarted Atom, closing all windows, but the package still does not appear in the menu and cannot be searched for nor run.

**Comment by jackputtock** [comment]
That seems to do with Atom itself possibly. But the actual plugin itself could not be installing correctly. Did you install via command line or via the Atom client?

**Comment by gantonia** [comment]
I originally installed (globally) via the command line... but when it didn't appear in the menu, I re-installed it via Atom's package manager (where it appears as installed, and after several restarts "added time" to the Atom start, but still doesn't show up anywhere as an option to run/use).

**Comment by gantonia** [comment]
Took far too long to find(!) - but I did find a solution (rebuilding the packages worked)!:

  danielnieto  commented on May 22 
 This is because the package is incompatible with the new version of Atom, you can rebuild the packages for this latest version quite easily, follow these steps:   
   - Restart Atom
   - Bring up the command palette (cmd + shift + p) and type "incompatible packages: view"
   - That screen will list all the packages that need to be rebuilt, just click on the "Rebuild" button
   - Atom will ask you to restart it, do so, and that's it, Atom Live Server is now working
https://github.com/jas-chen/atom-live-server/issues/57
