### ISSUE TITLE
Contains native modules that were compiled for an earlier version of Atom.

### ISSUE THREAD

**Issue by benjaminr177** [jas-chen/atom-live-server#83]
Had problems starting up the package, after realising that there was a bug saying:

- <img width="1300" alt="screen shot 2017-07-30 at 17 11 08" src="https://user-images.githubusercontent.com/17594813/28754242-57f0d44e-754a-11e7-938c-b2dac766760b.png">
- **"Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom."**
- After rebuilding the packages, the live server began to work. My atom version is 1.18.0.

**Comment by jas-chen** [comment]
#57
