### ISSUE TITLE
You must save your project every time to see changes.

### ISSUE THREAD

**Issue by lvl0-i74134** [jas-chen/atom-live-server#84]
Changes only happen when I use "ctrl + s" and it's not really live. It should show changes immediately without any need to save the project.

**Comment by jas-chen** [comment]
@lvl0-i74134 there is no tool can do that on the earth.

**Comment by lvl0-i74134** [comment]
@jas-chen Really! Try **Brackets** which has the function built-in or if you like **Atom** to do so just try [this package](https://atom.io/packages/atom-html-preview) you have changes in couple seconds.

**Comment by jas-chen** [comment]
Brackets only works with Chrome and has some [limitations](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#other-limitations). Atom-html-preview doesn't event fire a real browser.

**Comment by lvl0-i74134** [comment]
Thanks for the answer.
