### ISSUE TITLE
failed to spawn command /usr/lib/bin/node. Make sure /usr/lib/bin/node is installed and on your PATH

### ISSUE THREAD

**Issue by N4thyra** [jas-chen/atom-live-server#86]
Hi,

I'm using Linux - Antegros and I'm trying to figure out how to change the path from which is this package looking for node by default. I've figured out that I can modify the path here

const node = path.resolve(process.env.NODE_PATH, '../../bin/node'); (atom-live-server.js)

But for some reason, I am always getting /lib/ in the path as well. 

I have installed node in /usr/bin/node  and this package is looking for node in /usr/lib/bin/node

edit: You can close this ticket. I've solved this issue by installing a console into ATOM, and directly using live-server running on node.js

**Comment by jas-chen** [comment]
Modify to `const node = '/usr/bin/node';`?
