### ISSUE TITLE
Keep Showing "Listing Directory /"

### ISSUE THREAD

**Issue by GJS153** [jas-chen/atom-live-server#89]
Every time I use atom-live-server, instead of showing me the page that I'm interested in, it keeps showing me "listing directory /" page, like this one below.

<img width="960" alt="1" src="https://user-images.githubusercontent.com/22566537/29645981-308d0206-8846-11e7-8022-c94eebe9def4.png">

Has anyone encountered the same problem?

I'm using atom 1.19.2x64, btw.

**Comment by Masterism88** [comment]
I am having the same problem. It worked fine for me with using just html. But I normally use rails and all it does it show the listing directory.

**Comment by kevinokt** [comment]
Fixed: I noticed that launching the server always opened the first folder at the top of my 'Projects' list, try dragging the project folder you're working on to the top and launch (Ctrl + Alt + L) the server again!

**Comment by Ibranista** [comment]
kevinokt , tnx it worked
