### ISSUE TITLE
How to change the root of LiveServer

### ISSUE THREAD

**Issue by wa1gon** [jas-chen/atom-live-server#9]
Sorry I am new to Atom and JavaScript.  However I can find a way to set the root of LiveServer to my dist directory.

Suggestions?

thanks

**Comment by jas-chen** [comment]
This package doesn't support this function, however you can open another atom editor window and open your dist directory and start Live Server.

**Comment by alabius** [comment]
Also have the same question, but what i did was to navigate formate from the root folder to where my document was
