### ISSUE TITLE
New version doesn't work on Mac!

### ISSUE THREAD

**Issue by sevensidedsilver** [jas-chen/atom-live-server#92]
I've just gotten a new Mac and immediately got Atom and this package, however I'm having trouble getting it to work. On my older mac (which I suppose has a different version of either atom or this package), there was a menu item to launch the server.

There's no keybindings for mac and going into the config and removing the 'alt' in the chord bind didn't work.

**Comment by GregJacobs82** [comment]
Doesnt work for me either

**Comment by jas-chen** [comment]
#57
