### ISSUE TITLE
Mac issue

### ISSUE THREAD

**Issue by ZsoltGemes** [jas-chen/atom-live-server#94]
I am on Mac, and I have installed the live server, I can see it and verify the installation in the settings but I can't start it and find it in the top menu. `Package ->??? it's not here. How can I solve this problem?
Thank you.
<img width="892" alt="screen shot 2017-09-11 at 14 21 23" src="https://user-images.githubusercontent.com/13223257/30274180-8f05bfa2-96fc-11e7-987d-a409ff4a7c65.png">

**Comment by matmunn** [comment]
If you press `Cmd + Alt + I` (capital i) and scroll to the top of the console do you see the below error message?
![image](https://user-images.githubusercontent.com/65853/30302255-1fc4302c-97a3-11e7-8a77-7e8d85aa7109.png)

**Comment by ZsoltGemes** [comment]
Hi there,

Thanks for your reply.
I see this error message:
<img width="555" alt="screen shot 2017-09-12 at 03 50 56" src="https://user-images.githubusercontent.com/13223257/30304425-c11928f0-976d-11e7-9c37-bbe89c6ae2ce.png">

**Comment by matmunn** [comment]
Have you tried rebuilding the native modules? This is the reason it isn't showing in the packages menu.

**Comment by ZsoltGemes** [comment]
no, I have not. Actually I don't know how to do it. Can you please tell me? Thank yu.

**Comment by matmunn** [comment]
Open a terminal window and try entering this:
```
cd ~/.atom/packages/atom-live-server
apm rebuild
```

**Comment by ZsoltGemes** [comment]
Thank you very much for your help! 
It says the command is not found
<img width="589" alt="screen shot 2017-09-12 at 04 13 45" src="https://user-images.githubusercontent.com/13223257/30305014-e3cf964c-9770-11e7-9881-8dabed668f43.png">

**Comment by jas-chen** [comment]
#57
