### ISSUE TITLE
Can't see any option to start live server.

### ISSUE THREAD

**Issue by wordpressxpert** [jas-chen/atom-live-server#95]
If you have a problem launching a live-server, please try following steps:

1. Make sure you use the right hotkeys. After v2.0.0, the keys became `ctrl-alt` combination.
2. Try launching live-server from top menu: `Package -> live-server -> Start Server` to see if it works. (Can't)

**Comment by matmunn** [comment]
If you press `Cmd + Alt + I` (capital i) and scroll to the top of the console do you see the below error message?
![image](https://user-images.githubusercontent.com/65853/30302255-1fc4302c-97a3-11e7-8a77-7e8d85aa7109.png)

**Comment by jas-chen** [comment]
#57
