### ISSUE TITLE
Live Server not appearing

### ISSUE THREAD

**Issue by thjperry** [jas-chen/atom-live-server#96]
After installation I don't see "Live Server" in my packages in the Menu bar even after restarting atom multiple times (macOS Sierra 10.12.6 on Atom 1.19.7)

**Comment by matmunn** [comment]
If you press `Cmd + Alt + I` (capital i) and scroll to the top of the console do you see the below error message?
![image](https://user-images.githubusercontent.com/65853/30302255-1fc4302c-97a3-11e7-8a77-7e8d85aa7109.png)

**Comment by jas-chen** [comment]
#57
